config/routes.rb
Mercadoanalytics::Application.routes.draw do

  root :to => 'items#index'

  get 'test' => 'fakes#test'
  get 'index' => 'fakes#index'

  get 'items/:id/listing' => 'items#see_listing'
  get 'items/:id/printqr'  => 'items#print_qr'
  get 'items/:id/modify' => 'items#modify_from_page'
  get 'items/:id/photo' => 'items#photo'
  get 'items/:id/addimage' => 'items#add_image_to_description'
  resources :items

  get 'users/:id/authorize' => 'users#authorize'
  resources :users
  match '/login' => 'users#login'
  match '/logout' => 'users#logout'

end

app/models/item.rb
class Item < ActiveRecord::Base
  attr_accessible :has_stock, :meli_id, :user_id, :meli_stock, :meli_title, :stock_tracked, :sold_quantity, :real_stock
  
  belongs_to :user
  
  def has_sales
    (@sold_quantity>0)
  end
  
  def add_image_to_description!(user)
    
    if !self.stock_tracked
       it = JSON.parse(user.get("/items/#{self.meli_id}").body)
       
       description = "<p><img src=\"http://mercadostock.herokuapp.com/items/#{self.id.to_s}/photo.jpg\" alt=\"Informacion actualizada de stock\" height=\"480\" width=\"640\"></p>"
     
       
        
        if it['sold_quantity']>0
          user.post_json("/items/#{self.meli_id}/descriptions",{"text"=> description})
        else
          desc= JSON.parse(user.get("/items/#{self.meli_id}/descriptions").body).first
          desc["text"] = desc["text"] + description
          user.put_json("/items/#{self.meli_id}/descriptions/#{desc["id"]}",desc)
        end
        
        self.stock_tracked = true
        self.save
    end
  end
  
  def self.get_all_for_user!(user)
    items = JSON.parse(user.get("/users/#{user.meli_user_id}/items/search").body)['results']
    items.each do |it|
      the_item = Item.where(:meli_id => it).first
      item_info = JSON.parse(user.get("/items/#{it}").body)
      
      if !the_item       
        the_item = Item.new(:meli_id => it)
        item_info = JSON.parse(user.get("/items/#{it}").body)
        
        the_item.user_id = user.id
        the_item.meli_stock = item_info['available_quantity']
        the_item.real_stock = item_info['available_quantity']
        
        the_item.has_stock = ( the_item.meli_stock > 0 ) ? true : false
        the_item.sold_quantity = item_info['sold_quantity'] 
        the_item.meli_title = item_info['title']
        the_item.stock_tracked = false
        
        the_item.save
      else
        the_item.sold_quantity = item_info['sold_quantity'] 
        the_item.meli_stock = item_info['available_quantity']
        the_item.save
      end

    end
  end
  
  def update_from_meli!(user)
    item_info = JSON.parse(user.get("/items/#{self.meli_id}").body)
    self.sold_quantity = item_info['sold_quantity'] 
    self.meli_stock = item_info['available_quantity']
    self.save
  end
  
  def modify_stuff!(user,act)
    case act
    when 'decrement_real_stock'
      if real_stock > 0
        self.real_stock -= 1
        if self.real_stock == 0
          self.has_stock = false
        end
      end
    when 'increment_real_stock'
      self.real_stock +=1
      self.has_stock = true
    when 'decrement_meli_stock'
      self.meli_stock -= 1
      item_info = {}
      item_info['available_quantity'] = self.meli_stock
      
      user.put_json("/items/#{self.meli_id}",item_info)
      
      
    when 'increment_meli_stock'
      self.meli_stock += 1
      item_info = {}
      item_info['available_quantity'] = self.meli_stock
      
      user.put_json("/items/#{self.meli_id}",item_info)
    when 'mark_no_stock'
      self.has_stock = false
    when 'mark_stock'
      self.has_stock = true
    end
    
    self.save
  end
  
  def get_listing_url(user)
    item_info = JSON.parse(user.get("/items/#{self.meli_id}").body)
    item_info['permalink']
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  
  before_filter :login_required, :only => ['show','index','new','edit','create','destroy','add_image_to_description']
  
  # GET /items
  # GET /items.json
  def index
    Item.get_all_for_user!(User.find(session[:user]))

    @items = Item.where(:user_id => session[:user]).all
    
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @items }
    end
  end

  # GET /items/1
  # GET /items/1.json
  def show
    @item = Item.find(params[:id])
    @item.update_from_meli!(User.find(session[:user]))
    
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @item }
      format.jpg { render :qrcode => "mercadostock.herokuapp.com/items/#{@item.id.to_s}" }
    end
  end

  # GET /items/new
  # GET /items/new.json
  def new
    @item = Item.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @item }
    end
  end

  # GET /items/1/edit
  def edit
    @item = Item.find(params[:id])
  end

  # POST /items
  # POST /items.json
  def create
    @item = Item.new(params[:item])

    respond_to do |format|
      if @item.save
        format.html { redirect_to @item, notice: 'Item was successfully created.' }
        format.json { render json: @item, status: :created, location: @item }
      else
        format.html { render action: "new" }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /items/1
  # PUT /items/1.json
  def update
    @item = Item.find(params[:id])

    respond_to do |format|
      if @item.update_attributes(params[:item])
        format.html { redirect_to @item, notice: 'Item was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end
  
  def photo
    @item = Item.find(params[:id])
    
    respond_to do |format|
     
      if @item.has_stock
        abs_filepath = 'app/assets/images/has_stock.jpg'
      else
        abs_filepath = 'app/assets/images/has_no_stock.jpg'
      end
      
      format.jpg do
        File.open(abs_filepath, 'rb') do |f|
          send_data f.read, :type => "image/jpeg", :disposition => "inline"
        end
      end
    end
    
    
  end

  # DELETE /items/1
  # DELETE /items/1.json
  def destroy
    @item = Item.find(params[:id])
    @item.destroy

    respond_to do |format|
      format.html { redirect_to items_url }
      format.json { head :no_content }
    end
  end
  
  def add_image_to_description
    @item = Item.find(params[:id])
    
    @item.add_image_to_description!(User.find(session[:user]))
    
    respond_to do |format|
      format.html {redirect_to @item}
      format.json {render json: @item}
    end
  end
  
  def modify_from_page
    @item = Item.find(params[:id])
    
    @item.modify_stuff!(User.find(session[:user]),params[:modify_action])
   
    
    respond_to do |format|
      format.html {redirect_to @item}
      format.json {render json: @item}
    end
  end
  
  def print_qr
    @item = Item.find(params[:id])
    
    respond_to do |format|
      format.html
    end
  end
  
  def see_listing
    @item = Item.find(params[:id])
    respond_to do |format|
      format.html {redirect_to @item.get_listing_url(User.find(session[:user]))}
    end
  end
  
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/_form.html.erb
<%= form_for(@item) do |f| %>
  <% if @item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@item.errors.count, "error") %> prohibited this item from being saved:</h2>

      <ul>
      <% @item.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :meli_id %><br />
    <%= f.text_field :meli_id %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br />
    <%= f.number_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :has_stock %><br />
    <%= f.check_box :has_stock %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/items/edit.html.erb
<h1>Editing item</h1>

<%= render 'form' %>

<%= link_to 'Show', @item %> |
<%= link_to 'Back', items_path %>

app/views/items/index.html.erb
<div id="nav">
  <div class="row">
    <h2 class="text-center">MercadoStock</h2>
  </div>
</div>
<% @items.each do |item| %>
<div class="hide-for-small" style="margin-top:25px;"></div>
<div class="show-for-small item" style="background-color:#27AE60;">
    <div class="row">
      <div class="ten mobile-three columns title">
        <a href="<%= item_path item %>">
          <h5><%= item.meli_title %></h5>
          </a>
      </div>
        <div class="two mobile-one columns status">
          <a href="<%= item.stock_tracked ? (url_for(:controller => 'items', :action => 'modify_from_page', :id => item.id,:modify_action => (item.has_stock ? 'mark_no_stock' : 'mark_stock'))) : url_for(item) %>">
            <h3 class="text-center" style="font-size:31px;"><i class="general foundicon-<%= 'checkmark' if item.has_stock && item.stock_tracked %><%= 'remove' if !item.has_stock && item.stock_tracked%><%= 'settings' if !item.stock_tracked %>"></i></h3>
            </a>
        </div>
    </div>
</div>
<div class="hide-for-small item">
  <div class="row">
      <div class="ten mobile-three columns title">
        <a href="<%= item_path item %>">
          <h5><%= item.meli_title %></h5>
          </a>
      </div>
        <div class="two mobile-one columns status">
          <a href="<%= item.stock_tracked ? (url_for(:controller => 'items', :action => 'modify_from_page', :id => item.id,:modify_action => (item.has_stock ? 'mark_no_stock' : 'mark_stock'))) : url_for(item) %>">
            <h5 class="text-center" style="font-size:16px"><i class="general foundicon-<%= 'checkmark' if item.has_stock && item.stock_tracked %><%= 'remove' if !item.has_stock && item.stock_tracked%><%= 'settings' if !item.stock_tracked %>"></i></h5>
            </a>
        </div>
    </div>
</div>
<% end %>

app/views/items/new.html.erb
<h1>New item</h1>

<%= render 'form' %>

<%= link_to 'Back', items_path %>

app/views/items/print_qr.html.erb
<div class="listing">
  <div class="row title">
    <h1><%= @item.meli_title %></h1>
  </div>
  <div class="row gadgets">
    <div class="four columns">
      
    </div>
    <div class="four columns">
      <div class="panel">
        <img src="<%= url_for(@item) + '.jpg' %>">
      </div>
    </div>
    <div class="four columns">
      
        
    </div>
  </div>
</div>

app/views/items/show.html.erb
<div id="nav">
  <div class="row">
    <div class="two mobile-one columns"><a href="<%= url_for(:controller => 'items', :action => 'index') %>"><h3><i class="general foundicon-left-arrow"></i></h3></a></div>
    <div class="ten mobile-three columns"><h3 class="show-for-small" style="margin-left:18%;">Detalles</h3><h3 class="hide-for-small" style="margin-left:30%;">Detalles</h3></div>
  </div>
</div>

<div class="listing">
  <div class="hide-for-small" style="margin-top:50px;"></div>
  <div class="row header" style="margin-bottom:2px;">
    <div class="twelve columns">
      <h5><%= @item.meli_title %></h5>
    </div>
  </div>
  <div class="hide-for-small" style="margin-top:50px;"></div>
<% if @item.stock_tracked %>
  <div class="row">
    <div class="three offset-by-one columns status item">
      <div class="row">
        <div class="eight mobile-three columns"><h3 class="text-center">status</h3></div>
        <div class="four mobile-one columns"><h4 class="text-center"><i class="general foundicon-<%= 'checkmark' if @item.has_stock %><%= 'remove' if !@item.has_stock %>"></i></h4></div>
      </div>
      <div class="row title">
        <a href="<%= url_for(:controller => 'items', :action => 'modify_from_page', :modify_action => (@item.has_stock ? 'mark_no_stock' : 'mark_stock')) %>"><div class="twelve columns"><h5 class="text-center" style="font-size:19px;">Toggle</h5></div></a>
      </div>
    </div>
    <div class="three offset-by-one columns status item">
      <div class="row">
        <div class="eight mobile-three columns"><h3 class="text-center">stock ML</h3></div>
        <div class="four mobile-one columns"><h3 class="text-center"><%= @item.meli_stock %></h3></div>
      </div>
      <div class="row title">
        <div class="six mobile-two columns"><a href="<%= url_for(:controller => 'items', :action => 'modify_from_page', :modify_action => 'decrement_meli_stock') %>"><h5 class="text-center"><i class="general foundicon-minus"></i></h5></a></div>
        <div class="six mobile-two columns"><a href="<%= url_for(:controller => 'items', :action => 'modify_from_page', :modify_action => 'increment_meli_stock') %>"><h5 class="text-center"><i class="general foundicon-plus"></i></h5></a></div>
      </div>
    </div>
    <div class="three offset-by-one columns status item">
      <div class="row">
        <div class="eight mobile-three columns"><h3 class="text-center show-for-small">stock real</h3><h3 class="hide-for-small">stock real</h3></div>
        <div class="four mobile-one columns"><h3 class="text-center"><%= @item.real_stock %></h3></div>
      </div>
      <div class="row title">
        <div class="six mobile-two columns"><a href="<%= url_for(:controller => 'items', :action => 'modify_from_page', :modify_action => 'decrement_real_stock') %>"><h5 class="text-center"><i class="general foundicon-minus"></i></h5></a></div>
        <div class="six mobile-two columns"><a href="<%= url_for(:controller => 'items', :action => 'modify_from_page', :modify_action => 'increment_real_stock') %>"><h5 class="text-center"><i class="general foundicon-plus"></i></h5></a></div>
      </div>
    </div>
  </div>
  <div class="hide-for-small" style="margin-top:50px;"></div>
  <div class="row">
    <div class="five columns" style="margin-bottom:2px; background-color: #16A085;"><a href="<%= url_for(:controller => 'items', :action => 'print_qr', :id => @item.id) %>"><h5 class="text-center">Imprimir QR</h5></a></div>
    <div class="five offset-by-two columns" style="margin-bottom:2px; background-color: #16A085;"><a href="<%= url_for(:controller => 'items', :action => 'see_listing', :id => @item.id) %>"><h5 class="text-center">Ir a MercadoLibre</h5></a></div>
  </div>
</div>
<% else %>
  <div class="row">
    <a href="<%= url_for(:controller => 'items', :action => 'add_image_to_description', :id => @item.id) %>">
      <div class="eight columns status item centered">
        <div class="megamo"><h1 class="text-center">Activar</h1></div>
      </div>
    </a>
  </div>
<% end %>